---
title: "lab9"
output: html_document
date: "2022-09-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr) 
library(spData)
library(sf)  
library(terra) 
library(tidyr)
```
## Vector Data
```{r}
methods(class = "sf") 
```
```{r}
class(world)
```

```{r}
dim(world)

```

```{r}
head(world)
```

```{r}
world_df = st_drop_geometry(world)
class(world_df)
```

```{r}
ncol(world_df)
```
```{r}
head(world_df)
```

## Subsetting
```{r}
world[1:6, ]
```

```{r}
world[, 1:3] 
```

```{r}
world[1:6, 1:3]
```

```{r}
world[, c("name_long", "pop")]
```
```{r}
world[, c(T, T, F, F, F, F, F, T, T, F, F)] # by logical indices
```



## Your turn question 1

```{r}
# first let's find the position of the two specified columns
p1<-grep("subregion", colnames(world))
p2<- grep("gdpPercap", colnames(world))

#then put the positions in query

world[5:10, c(p1,p2)]
```


## Your turn question 2

```{r}
world[5:10,c("subregion", "gdpPercap")]
```
```{r}
i_small <- world$area_km2 < 10000
summary(i_small) # a logical vector

```

```{r}
small_countries <- world[i_small, ]
small_countries
```

```{r}
small_countries <- world[world$area_km2 < 10000, ]
# Same as:
small_countries <- subset(world, area_km2 < 10000)
```

## Your turn  question 3
```{r}
#First let's check the exact name of western asian region
unique(world$subregion)
```
```{r}
# It's western asia. Let's subset it now.

West_Asia <- world[world$subregion == "Western Asia", ]
West_Asia
```

```{r}
world1 <- dplyr::select(world, name_long, pop)
colnames(world1)
```

```{r}
# all columns between name_long and pop (inclusive)
world2 <- dplyr::select(world, name_long:pop)

# all columns except subregion and area_km2 (inclusive)
world3 <- dplyr::select(world, -subregion, -area_km2)
```

```{r}
world4 <- dplyr::select(world, name_long, population = pop)
colnames(world4)
```

```{r}
# We can generate the same results using the base R command, but with much longer codes
world5 <- world[, c("name_long", "pop")] # subset columns by name
names(world5)[names(world5) == "pop"] = "population" # rename column manually

```

```{r}
pull(world, pop)
```
```{r}
world$pop
```

```{r}
world[["pop"]]
```


```{r}
world7 <- filter(world, area_km2 < 10000) # countries with a small area
world7 <- filter(world, lifeExp > 82)      # with high life expectancy

```

## Chaining commands with pipes


```{r}
world7 <- world %>%
  filter(continent == "Asia") %>%
  dplyr::select(name_long, continent) %>%
  slice(1:5)
world7
```

## Your turn question 4
```{r}
world4 <- world %>%
  filter(continent=="Africa") %>%
  select(name_long , subregion) %>%
  slice(10:20)

world4
```
## Aggregation 

```{r}
world_agg1 <- aggregate(pop ~ continent, FUN = sum, data = world, na.rm = TRUE)
class(world_agg1) # it's a data frame
```

```{r}
world_agg2 <- aggregate(world["pop"], list(world$continent), FUN = sum, na.rm = TRUE)
class(world_agg2) # it's an sf object
```

```{r}
nrow(world_agg2)
```

```{r}
world_agg3 <- world %>%
  group_by(continent) %>%
  summarize(pop = sum(pop, na.rm = TRUE))
world_agg3
```

```{r}
world_agg4  <- world %>% 
  group_by(continent) %>%
  summarize(pop = sum(pop, na.rm = TRUE), `area (sqkm)` = sum(area_km2), n = n())
world_agg4
```

```{r}
world_agg5 <- world %>% 
  st_drop_geometry() %>%                      # drop the geometry for speed
  dplyr::select(pop, continent, area_km2) %>% # subset the columns of interest  
  group_by(continent) %>%                     # group by continent and summarize:
  summarize(Pop = sum(pop, na.rm = TRUE), Area = sum(area_km2), N = n()) %>%
  mutate(Density = round(Pop / Area)) %>%     # calculate population density
  top_n(n = 3, wt = Pop) %>%                  # keep only the top 3
  arrange(desc(N))                            # arrange in order of n. countries, descending
world_agg5
```
```{r}
dim(coffee_data)
```
```{r}
head(coffee_data)
```

```{r}
world_coffee <- left_join(world, coffee_data)
```
```{r}
class(world_coffee)
```

```{r}
head(world_coffee)
```
```{r}
plot(world_coffee["coffee_production_2017"])
```
```{r}
coffee_renamed <- rename(coffee_data, nm = name_long)
world_coffee2 <- left_join(world, coffee_renamed, by = c(name_long = "nm"))
head(world_coffee2)
```

```{r}
coffee_renamed <- rename(coffee_data, nm = name_long)
world_coffee2 <- left_join(world, coffee_renamed, by = c(name_long = "nm"))
head(world_coffee2)
```

```{r}
dim(world_coffee2)
```

```{r}
world_coffee_inner <- inner_join(world, coffee_data)
```

```{r}
dim(world_coffee_inner)
```

```{r}
setdiff(coffee_data$name_long, world$name_long)

```

```{r}
(drc <- stringr::str_subset(world$name_long, "Dem*.+Congo"))
```

```{r}
coffee_data$name_long[grepl("Congo,", coffee_data$name_long)] = drc
world_coffee_match <- inner_join(world, coffee_data)
```

```{r}
nrow(world_coffee_match)
```

```{r}
coffee_world <- left_join(coffee_data, world)
```

```{r}
class(coffee_world)
```
## Adding and Removing columns
```{r}
world_new <- world # do not overwrite our original data
world_new$pop_dens <- world_new$pop / world_new$area_km2
```

```{r}
world %>% 
  mutate(pop_dens = pop / area_km2)
```

```{r}
world %>% 
  transmute(pop_dens = pop / area_km2)
```

```{r}
world_unite <- world %>%
  unite("con_reg", continent:region_un, sep = ":", remove = TRUE)
head(world_unite)
```

```{r}
world_separate <- world_unite %>% 
  separate(con_reg, c("continent", "region_un"), sep = ":")
head(world_separate)
```

```{r}
world %>% 
  rename(name = name_long)
```
## Your turn question 5
```{r}
worldYT <- world %>%
  mutate(gdp = gdpPercap*pop) %>%
  rename(nationalGDP=gdp)

head(worldYT)
```

```{r}
new_names = c("i", "n", "c", "r", "s", "t", "a", "p", "l", "gP", "geom")
world %>% 
  setNames(new_names)
```

```{r}
world_data = world %>% st_drop_geometry()
class(world_data)
```

## raster data

```{r}
# Making a raster dataset from scratch to use in this example. 
elev = rast(nrows = 6, ncols = 6, resolution = 0.5, 
            xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,
            vals = 1:36)
plot(elev)
```

```{r}
grain_order = c("clay", "silt", "sand")
grain_char = sample(grain_order, 36, replace = TRUE)
grain_fact = factor(grain_char, levels = grain_order)
grain = rast(nrows = 6, ncols = 6, resolution = 0.5, 
             xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,
             vals = grain_fact)
plot(grain)
```

```{r}
levels(grain)[[1]] = c(levels(grain)[[1]], wetness = c("wet", "moist", "dry"))
```

```{r}
levels(grain)
```

## Subsetting raster data
```{r}
elev[1,1]
```
```{r}
elev[1]
```

```{r}
elev[1,1]=0
elev[]
```

```{r}
elev[1, c(1, 2)] = 0
```

## Summarizing raster objects
```{r}
#install.packages("globals")
library(globals)
global(elev, sd)
hist(elev)
```

