---
title: "lab10"
output: html_document
date: "2022-09-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
library(GISTools)
library(sf)
library(terra)
library(spData)
library(tmap)
```

```{r}
data(nz)
data(nz_height)
canterbury <- nz %>% filter(Name=="Canterbury")
canterbury_height <- nz_height[canterbury,]

t1<- qtm(nz, fill="white") + qtm(nz_height, symbols.col = "red")

t2<- qtm(nz, fill="white") + qtm(canterbury_height, symbols.col = "red")

tmap_arrange(t1,t2)
```

```{r}
nz_height[canterbury,,op=st_intersects]
```

```{r}
sel_sgbp <- st_intersects(x=nz_height, y=canterbury)
class(sel_sgbp)
```

```{r}
sel_logical <- lengths(sel_sgbp) > 0
canterbury_height2 <- nz_height[sel_logical,]

qtm(canterbury) + qtm(canterbury_height2)

```
```{r}
canterbury_height3 <- nz_height %>%
  st_filter(y=canterbury, .predicate=st_intersects)

qtm(canterbury) + qtm(canterbury_height3)
```

# Topological relations
```{r}
polygon_matrix <- cbind(x=c(0,0,1,1,0), y=c(0,1,1,.5,0))
polygon_sfc <- st_sfc(st_polygon(list(polygon_matrix)))
```

```{r}
plot(polygon_sfc)
```

```{r}
line_sfc = st_sfc(st_linestring(cbind(
  x = c(0.4, 1),
  y = c(0.2, 0.5)
)))


point_df = data.frame(
  x=c(.2,.7,.4),
  y=c(.1,.2,.8)
  )
                  
point_sf <- st_as_sf(point_df, coords = c("x", "y"))

plot(line_sfc)
```

# My turn 01
```{r}
qtm(polygon_sfc, fill = "cyan") + qtm(line_sfc, lines.col  = "blue", lines.lwd = 5.5) + qtm(point_sf, symbols.col = "orange")
```

```{r}
st_intersects(point_sf, polygon_sfc)
```
```{r}
st_intersects(point_sf, polygon_sfc, sparse = FALSE)

```

```{r}
st_within(point_sf, polygon_sfc)

```

```{r}
st_touches(point_sf, polygon_sfc)

```
```{r}
st_disjoint(point_sf, polygon_sfc, sparse = FALSE)

```

```{r}
st_is_within_distance(point_sf, polygon_sfc, dist = .2, sparse = FALSE)[,1]

```
# Spatial join

```{r}
set.seed(2018)
(bb = st_bbox(world))
```


```{r}
random_df <- data.frame(x= runif(n=10, min = bb[1], max = bb[3]), y = runif(n=10, min=bb[2], max=bb[4]))  #making random 10 points

random_points <- random_df %>%
  st_as_sf(coords = c("x", "y")) %>%
  st_set_crs("EPSG:4326")  #using those points as coorinates and projecting those



world_random = world[random_points, ]  #clipping world where random points are

nrow(world_random)
```
```{r}
random_joined = st_join(random_points, world["name_long"])

head(random_joined, 10)

```


```{r}
qtm(world) + qtm(random_points, symbols.col = "red")

qtm(world_random) + qtm(random_points, symbols.col = "red")
```
# Non Overlapping joins
```{r}
data("cycle_hire")
data("cycle_hire_osm")

plot(st_geometry(cycle_hire), col = "blue")

plot(st_geometry(cycle_hire_osm), add=TRUE, pch=4, col = "orange")

```



```{r}
any(st_touches(cycle_hire, cycle_hire_osm, sparse = FALSE))

```
```{r}
sel <- st_is_within_distance(cycle_hire, cycle_hire_osm, dist = 20) #to see how many points of osm are 20 m apart from cycle_hire. 
summary(lengths(sel)>0)
```

```{r}
z = st_join(cycle_hire, cycle_hire_osm, st_is_within_distance, dist=20) #add osm which are 20 m apart with cycle hire
nrow(cycle_hire)

```
```{r}
nrow(z) #it's more than cycle_hire because multiple points from osm got matched.
```
```{r}
z = z %>% 
  group_by(id) %>%
  summarise(capacity=mean(capacity)) #so taking the mean of the matched points

nrow(z) #now they are same. voila!
```

```{r}

plot(cycle_hire_osm["capacity"])
```

```{r}
plot(z["capacity"])
```

# Spatial Aggregation
```{r}
nz_agg = aggregate(x=nz_height, by=nz, FUN=mean)

#identical(st_geometry(nz), st_geometry(nz_agg))

# the aggregate method can be done by dplyr too

nz_agg2 = st_join(x=nz, y=nz_height) %>%
  group_by(Name) %>%
  summarise(elevation=mean(elevation, na.rm=TRUE))

```

# My turn 3
```{r}
tm_shape(nz_agg2) +
  tm_polygons("elevation")
```

# Distance

```{r}
nz_highest = nz_height %>% top_n(n=1, wt=elevation)

canterbury_centroid = st_centroid(canterbury)
```

```{r}
st_distance(nz_highest, canterbury_centroid)
```
```{r}
co = filter(nz, grepl("Canter|Otag", Name))

st_distance(nz_height[1:3, ], co)
```
```{r}
plot(st_geometry(co)[2])
plot(st_geometry(nz_height)[2:3], add=TRUE)
```

